version: "3.8"
services:
  mongo:
    image: mongo
    container_name: mongo_c
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017" # Corrected syntax

  api:
    build: ./server
    container_name: server_c
    ports:
      - "3001:3001" # Corrected syntax
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydb
  client:
    build: ./client
    container_name: client_c
    ports:
      - "3000:3000"
    stdin_open: true
    tty: true
    depends_on:
      - api
    volumes:
      - ./client:/client
      - /client/node_modules

volumes:
  mongo-data:
